version: '3'

includes:
  win: ./Taskfile_windows.yml
  
tasks:

  check-virtualenv:
    silent: true
    cmds:
      - echo "Check .env folder"
      - test -d .venv
      - echo -n "Check if virtual environment is active-> " && python -c "import sys; print('virtualenv is active' if sys.prefix != sys.base_prefix else 'virtualenv is NOT active')"
      - python -c "import sys; exit(1 if sys.prefix == sys.base_prefix else 0)"
      - python --version

  clean-all:
    deps: [check-virtualenv]
    cmds:
      - task: clean-build
      - task: clean-pyc
      - task: clean-test

  clean-build:
    deps: [check-virtualenv]
    cmds:
      - echo "remove build artifacts"
      - rm -fr build/
      - rm -fr dist/
      - rm -fr .eggs/
      - find . -name '*.egg-info' -exec rm -fr {} +
      - find . -name '*.egg' -exec rm -f {} +

  clean-pyc:
    deps: [check-virtualenv]
    cmds:
      - echo "remove Python file artifacts"
      - find . -name '*.pyc' -exec rm -f {} +
      - find . -name '*.pyo' -exec rm -f {} +
      - find . -name '*~' -exec rm -f {} +
      - find . -name '__pycache__' -exec rm -fr {} +

  clean-test:
    deps: [check-virtualenv]
    cmds:
      - echo "remove test and coverage artifacts"
      - rm -fr .tox/
      - rm -f .coverage
      - rm -fr htmlcov/
      - rm -fr .pytest_cache

  run:
    deps: [check-virtualenv]
    cmds:
      - python --version

  dist:
    deps: [check-virtualenv]
    cmds:  
      - echo "builds source and wheel package"
      - task: clean-all
      - python setup.py sdist
      - python setup.py bdist_wheel
      - ls -l dist